name = "hateb-to-bluesky"
main = "src/index.ts"
compatibility_date = "2024-01-29"

# 環境変数
[env.production.vars]

# Bluesky に投稿する本文のテンプレート
#  %title% - 元記事のタイトル
#  %link% - 元記事の URL
#  %description% - はてなブックマークのコメント
TEXT_TEMPLATE = "%title%\n%link%\n\n%description%"

# Cron トリガー設定
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ["*/15 * * * *"] # 15 分間隔で実行

# ↓ は Github Actions でのデプロイ時に自動的に書かれる
# [env.production]
# kv_namespaces = [{ binding = "KV", id = "xxx" }]
