name: Deploy

on:
  push:
    branches:
      - main
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          preCommands: |
            wrangler kv:namespace create KV_HATEB_BSKY || true

            echo "[[env.production.kv_namespaces]]" >> wrangler.toml
            echo "binding = \"KV\"" >> wrangler.toml
            echo "id = \""$(npx wrangler kv:namespace list | jq -r '.[] | select(.title | endswith("KV_HATEB_BSKY")) | .id')"\"" >> wrangler.toml
            tail -n 3 wrangler.toml
          environment: production
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
