name: Deploy

on:
  push:
    branches:
      - main
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
        preCommands: |
          wrangler kv:namespace create KV_HATEB_BSKY || true
          export KV_HATEB_BSKY_ID=$(wrangler kv:namespace list | jq -r '.[] | select(.title | endswith("KV_HATEB_BSKY")) | .id')
          echo "[env.production]" >> wrangler.toml
          echo "kv_namespaces = [{binding=\"KV\", id=\"${KV_HATEB_BSKY_ID}\"}]" >> wrangler.toml
        environment: production
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
